name: Sync Upstream
 
on:
  schedule:
    - cron: '30 20 * * *'
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
 
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
 
      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/thoughtspot/tse-demo-builder-v2.git
          git fetch upstream
 
      - name: Merge upstream/main into your main branch
        run: |
         if git branch -r | grep 'upstream/main'; then
            UPSTREAM_BRANCH="upstream/main"
          elif git branch -r | grep 'upstream/master'; then
            UPSTREAM_BRANCH="upstream/master"
          else
            echo "::error::Could not find 'main' or 'master' branch on the 'upstream' remote."
            exit 1
          fi
          echo "Merging changes from $UPSTREAM_BRANCH into main..."
          # 3. Merge the found branch. The --allow-unrelated-histories flag
          #    is kept for initial syncs, but can be removed later.
          git merge $UPSTREAM_BRANCH --allow-unrelated-histories -m "Merge upstream changes"
 
      - name: Push changes to your repository
        run: git push origin main
 
      - name: Notify Repo Owner and Developer if Sync Fails
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: " Sync Upstream Failed - ${{ github.repository }}"
          to: |
            repoowner@example.com,  
            aparnaa.marimuthu@7dxperts.com
          from: "GitHub Actions <no-reply@github.com>"
          body: |
            Hi Team,
 
            The **Sync Upstream** GitHub Action has failed for the repository:
             ${{ github.repository }}
 
            Please review the latest run logs for more details:
             ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
            — GitHub Actions Bot